Second Task
pejath/TestGuru pull request #2
Opened 2023-02-15 11:18 UTC by pejath

* Categories model
  * title 
* Tests model
  * title
  * level
  * category_id
* Questions model
  * body
  * test_id 
* Answers model
  * body
  * correct
  * question_id 
* User model
  * username
  * email
  * role

2023-02-15 14:48 UTC, VidgarVii requested changes

2023-02-15 14:48 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
ссоциации позже будут в курсе
пока лучше убери их из моделей, чтобы они не отвлекали. Тем более они объявлены не верно.
Нам на данном этапе внешних ключей в таблицах вполне достаточно ближайшие пару уроков нужно будет ручками конструировать запросы, чтобы лучше понять, как ассоциации работают, а потом уже будем использовать ассоциации

2023-02-15 14:48 UTC, VidgarVii commented on db/migrate/20230215110231_create_tests.rb
> +      t.integer :level, default: 1
стоит добавить еще null: false
тесты без уровней не будет.

2023-02-15 14:48 UTC, VidgarVii commented on db/migrate/20230215110231_create_tests.rb
> +
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2023-02-15 14:48 UTC, VidgarVii commented on db/migrate/20230215110513_create_answers.rb
> +      t.boolean :correct, default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2023-02-15 14:48 UTC, VidgarVii commented on db/migrate/20230215110513_create_answers.rb
> +      t.string :body
null: false

2023-02-15 16:34 UTC, pejath commented on db/migrate/20230215110513_create_answers.rb
> +      t.string :body
как по мне, это не логично, так как пользователь может не знать ответа и захочет отправить пустую строку

2023-02-16 06:05 UTC, VidgarVii commented on db/migrate/20230215110231_create_tests.rb
> +      t.belongs_to :author, null: false, foreign_key: {to_table: :users}
`{ to_table: :users }`

2023-02-19 18:08 UTC, merged