Task 4
pejath/TestGuru pull request #4
Opened 2023-02-20 21:17 UTC by pejath

* feat: added associations

2023-02-21 07:18 UTC, VidgarVii requested changes

2023-02-21 07:18 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests
если категорию удалить, то в текущем варианте можно в дальнейшем получить ошибку

к примеру при попытке обратиться по ассоциации (`@test.category`)
или при каких-то операциях, которые подразумевают валидацию объекта

после удаления категории в таблице `tests` останется в поле `category_id` ссылка на несуществующий объект
т.е. объекты в таблице `tests` станут невалидными: рельсы по умолчанию проверяют наличие ассоциированного объекта для всех `belongs_to` ассоциаций (при валидации этого объекта) и выбрасывают ошибку валидации, если объекта не существует

если же на уровне бд поле `category_id` обозначено, как внешний ключ, то уже на попытке удаления объекта из таблицы `categories` получим ошибку базы данных, такого примерно вида:
```
ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: EROR:  update or delete on table "categories" violates foreign key constraint
```
и рельсы откажутся удалять категорию

поэтому для всех `has_*` ассоциаций следует указывать поведение при удалении - можно посмотреть в документации - опция `dependent: ...`

2023-02-21 07:18 UTC, VidgarVii commented on app/models/question.rb
> +  has_many :answers
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2023-02-21 07:18 UTC, VidgarVii commented on app/models/test.rb
> +                    .order(title: :desc).pluck(:title)
отступы уехали. Используй рубокоп для проверки кода

2023-02-21 08:06 UTC, pejath commented on app/models/test.rb
> +                    .order(title: :desc).pluck(:title)
@VidgarVii здесь отступы по Rubocop, я перед коммитом всегда проверяю

2023-02-21 11:54 UTC, pejath commented on db/migrate/20230215110231_create_tests.rb
> +      t.belongs_to :author, null: true, foreign_key: { to_table: :users }
Как мне кажется, тест не должен удаляться, если удалили автора теста, а проверку на null можно в последующем сделать через валидации

2023-02-21 11:54 UTC, pejath commented on app/models/user.rb
> +    tests.where(level:)
я знаю про данный синтаксис, ruby автоматически в хэш подставляет одноименную переменную если ее не указывать

2023-02-21 13:51 UTC, VidgarVii requested changes

2023-02-21 13:51 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: :author_id
а в схеме указано, что автора может не быть. Где ошибка?

http://rusrails.ru/active-record-associations#optional

2023-02-21 13:51 UTC, VidgarVii commented on app/models/test.rb
> +                    .order(title: :desc).pluck(:title)
```ruby
joins(:category)
  .where(categories: { title: category_tile })
  .order(title: :desc)
  .pluck(:title)
```
так лучше читается

2023-02-21 13:51 UTC, VidgarVii commented on db/migrate/20230219211346_create_results.rb
> +    add_index :results, %i[user_id test_id], unique: true
это нормально когда юзер проходит один и тот же тест несколько раз

2023-02-21 13:51 UTC, VidgarVii commented on db/migrate/20230215110231_create_tests.rb
> +      t.belongs_to :author, null: true, foreign_key: { to_table: :users }
Валидация не нужна. В ассоциациях проверка на нул стоит автоматически. Надо использовать опцию optional

2023-02-22 05:17 UTC, VidgarVii requested changes

2023-02-22 05:17 UTC, VidgarVii commented on app/models/test.rb
> +                    .order(title: :desc)
для отступов всегда используют 2 пробела!

2023-02-22 05:17 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: :author_id, optional: false
optional: false
получается что автор нужен, что противоречит схеме, миграции и ассоциации у юзера. Давай уже определимся, автор нужен или нет?

2023-02-22 05:29 UTC, pejath commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: :author_id, optional: false
Автор нужен при создании

2023-02-22 05:57 UTC, pejath commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: :author_id, optional: false
@VidgarVii мне кажется моя идея [https://github.com/pejath/TestGuru/pull/4#discussion_r1112950135](urb) вполне понятна, да, получается модель противоречит схеме, но тогда для чего существует документация и почему нельзя сделать как я сделал? В последствии добавить `validates_presence_of :author_id, on: :create` поскольку как я понимаю подобный механизм невозможно реализовать на миграции

2023-02-22 13:36 UTC, VidgarVii requested changes

2023-02-22 13:36 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User', foreign_key: :author_id, optional: false
1 потому что это противоречит уже объявленным схеме, миграции и ассоциации у юзера.
2 validates_presence_of легаси метод уже много лет. Используют validates или validate
3 Писать надо код так чтобы не пришлось его переписывать. А только дополнять.
Мне не понятно почему я должен принять сейчас заведомо противоречивый код.

2023-02-22 17:09 UTC, merged