Task 6
pejath/TestGuru pull request #6
Opened 2023-02-25 15:46 UTC by pejath

* added routes
* new tests_controller and tests views
* new questions_controller questions views

2023-02-26 10:04 UTC, VidgarVii requested changes

2023-02-26 10:04 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    # render json: { questions: Question.all }
данные комментарии не несут ни какой полезной информации. А только отвлекают. Такое нельзя оставлять в коде. ПР должен содержать только рабочий код.

2023-02-26 10:04 UTC, VidgarVii commented on config/routes.rb
> +    resources :questions
для "облегчения" роутинга рекомендуется использовать (где это возможно и приемлемо) опцию `shallow: true`
Это уменьшит кол-во запросов в контроллере. Упростит код и укоротит http запрос
http://rusrails.ru/rails-routing#melkoe-vlozhenie

2023-02-26 10:04 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @test.questions.build
данный экшен ничего не передаёт во вью в форму

2023-02-26 10:04 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<!DOCTYPE html>
в шаблонах не пишут хтмл полностью. т.е. DOCTYPE html head body.
Части кода из этих файлов вставляются в application.html.erb
Тут достаточно было написать форму

2023-02-26 10:04 UTC, VidgarVii commented on app/views/questions/new.html.erb
> +<form action="/tests/<%= @test.id %>/questions" method="post">
тут баг из-за не верного экшена

2023-02-26 10:04 UTC, VidgarVii commented on app/views/questions/show.json.jbuilder
> +# frozen_string_literal: true
эти все jbuilder можно и нужно удалять. Рельса сама сериалзиует данные в json если использовать render :json. 
По ТЗ нет задания возвращать разные форматы данных.

2023-02-26 10:04 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :questions
протестируй удаление теста когда у него есть вопросы

2023-02-26 10:04 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
если ресурс по каким-то причинам не удаляется, то это баг и его надо исправлять, ане показывать юзеру

2023-02-26 10:04 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
respond_to не нужен. Мы не будем возвращать разные типы данных.
В ТЗ этого нет

2023-02-26 10:11 UTC, pejath commented on app/controllers/questions_controller.rb
> +    respond_to do |format|
Это сделано из расчета, что пользователь попробует удалить одну запись дважды

2023-02-26 13:10 UTC, pejath commented on app/views/questions/new.html.erb
> +<form action="/tests/<%= @test.id %>/questions" method="post">
`POST   /tests/:test_id/questions(.:format) questions#create` ?

2023-02-27 07:19 UTC, VidgarVii requested changes

2023-02-27 07:19 UTC, VidgarVii commented on app/helpers/answers_helper.rb
> +module AnswersHelper
в этом реквесте данные модули не нужны. В ТЗ они не требуются

2023-02-27 07:19 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    @question = @test.questions.create(question_params)
При создании и обновлении ресурса нужно проверять валидацию, которая была прописана в модели. И если валидация не прошла, то рендерят форму и выводит ошибки(ошибки будем показывать далее по уроку)
По этому тут надо добавить проверку, записался ли объект в базу?
стандартный подход экшена create такой
```
@question = @test.questions.build(question_params)
if @question.save
  redirect_to @question
else
  render :new
end
```

2023-02-27 07:19 UTC, VidgarVii commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
здесь и в `question_params` какая-то путанница...
в `question_params` не должен входить `test_id`, этот аттрибут идет в параметрах, но не под ключом `:question`
метод же `question_params` должен возвращать только аттрибуты идущие в параметрах под ключом `:question`
а остальные параметры вопроса как раз должны идти под ключом `:question` (в нашем случае `body`)

2023-02-27 07:19 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    if @test.destroy
про проверку удаления ресусра я писал выше

2023-02-27 08:04 UTC, pejath commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
@VidgarVii, это будет работать до тех пор пока нам не придется делать update, а так как в routes стоит 
`shallow: true` запрос на put в находится ` PUT  /questions/:id(.:format)  questions#update` и test_id предется передать через question_params

2023-02-27 08:13 UTC, pejath commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
конечно исходя из того что можно будет перенести вопрос из одного теста в другой

2023-02-27 15:19 UTC, merged